# Generated by Django 3.2.19 on 2023-06-20 16:59

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_auto_20230620_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='exercise_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='post',
            name='exercise_video',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='video'),
        ),
    ]
