# Generated by Django 3.2.19 on 2023-06-23 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0004_auto_20230623_1204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='workout',
            new_name='post',
        ),
    ]
