# Generated by Django 3.2.19 on 2023-06-23 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0006_alter_exercise_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='content',
            new_name='body',
        ),
    ]
