# Generated by Django 3.2.19 on 2023-06-23 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0008_alter_exercise_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('exercise_number', models.IntegerField()),
                ('body', models.TextField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='workout.post')),
            ],
            options={
                'ordering': ['exercise_number'],
            },
        ),
        migrations.DeleteModel(
            name='Exercise',
        ),
    ]
