# Generated by Django 3.2.19 on 2023-06-23 13:40

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0009_auto_20230623_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('exercise_number', models.IntegerField()),
                ('body', models.TextField()),
                ('exercise_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('exercise_video', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='video')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='workout.post')),
            ],
            options={
                'ordering': ['exercise_number'],
            },
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
