# Generated by Django 3.2.19 on 2023-06-23 17:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0010_auto_20230623_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='number_of_exercises',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(8)]),
        ),
    ]
