# Generated by Django 3.2.19 on 2023-06-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0011_alter_post_number_of_exercises'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='exercise_completed',
            field=models.BooleanField(default=False),
        ),
    ]
