# Generated by Django 3.2.19 on 2023-06-25 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0012_exercise_exercise_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
    ]
