# Generated by Django 3.2.19 on 2023-06-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0014_exercise_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
