# Generated by Django 3.2.19 on 2023-06-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0015_alter_exercise_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='exercise_number',
            field=models.PositiveIntegerField(),
        ),
    ]
