# Generated by Django 3.2.19 on 2023-06-27 19:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0016_alter_exercise_exercise_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='exercise_number',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='post',
            name='number_of_exercises',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)]),
        ),
    ]
