# Generated by Django 3.2.19 on 2023-06-27 22:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0017_auto_20230627_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='exercise_number',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)]),
        ),
        migrations.AlterField(
            model_name='post',
            name='number_of_exercises',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(8)]),
        ),
    ]
