# Generated by Django 3.2.19 on 2023-06-28 17:37

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0018_auto_20230627_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='exercise_video',
        ),
        migrations.AddField(
            model_name='exercise',
            name='exercise_muscle_group',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='muscle group image'),
        ),
    ]
