# Generated by Django 3.2.19 on 2023-06-28 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0022_auto_20230628_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='workout_start',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
