# Generated by Django 3.2.19 on 2023-06-30 18:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0024_auto_20230629_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='number_of_exercises',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(8)]),
        ),
    ]
