# Generated by Django 3.2.19 on 2023-06-30 22:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0025_alter_workout_number_of_exercises'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='number_of_exercises',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(8)]),
        ),
    ]
